name: lamit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  animated_custom_dropdown: ^1.5.0
  baseflow_plugin_template: ^2.1.1
  cached_network_image: null
  carousel_slider: ^4.1.1
  connectivity_plus: null
  contained_tab_bar_view: ^0.8.0
  cupertino_icons: ^1.0.2
  custom_searchable_dropdown: ^2.1.1
  datepicker_dropdown: ^0.0.7+2
  dio: ^4.0.6
  dropdown_button2: null
  dropdown_search: ^2.0.1
  dropdown_date_picker: ^0.1.1+2
  email_validator: ^2.1.17
  external_path: null
  fancy_containers: null
  firebase_auth: ^4.2.4
  firebase_core: null
  firebase_messaging: null
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  flutter_slider_drawer: ^2.1.1
  flutter_staggered_grid_view: ^0.6.2
  fluttertoast: ^8.0.9
  font_awesome_flutter: null
  geocoding: null
  geolocator: null
  get: 4.6.5
  google_fonts: ^4.0.3
  google_maps_flutter: null
  google_maps_place_picker_mb: ^2.0.0-mb.22
  hexcolor: null
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.17.0
  location: ^4.4.0
  maps_launcher: ^2.0.1
  nice_buttons: ^0.0.2
  open_filex: ^4.3.2
  open_location_picker: ^0.2.1
  pdf: ^3.8.4
  permission_handler: null
  pin_code_fields: ^7.4.0
  printing: ^5.9.3
  search_choices: ^2.1.7
  shared_preferences: ^2.0.15
  syncfusion_flutter_datepicker: ^20.3.50
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
